layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: cyrilfindeling
  stackoverflow: 3466492
  malt: cyrilfindeling
  cv: cv.pdf

skills:
  - name: Android
    web_url: https://developer.android.com/jetpack
    image_url: https://source.android.com/setup/images/Android_greenrobot.png
  
  - name: iOS
    web_url: https://developer.apple.com/
    image_url: ./assets/images/ios.png

  - name: Ruby on Rails
    web_url: https://rubyonrails.org/
    image_url: https://rubyonrails.org/images/rails-logo.svg

  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://kotlinlang.org/assets/images/open-graph/kotlin_250x250.png

  - name: Swift
    web_url: https://developer.apple.com/swift/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Swift_logo.svg/1138px-Swift_logo.svg.png
    
  - name: Unity
    web_url: https://unity.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/8/8a/Official_unity_logo.png