layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: cyrilfindeling
  stackoverflow: 3466492
  malt: cyrilfindeling

skills:
  - name: Android
    web_url: https://developer.android.com/jetpack
    image_url: https://source.android.com/setup/images/Android_greenrobot.png
  
  - name: iOS
    web_url: https://developer.apple.com/
    image_url: ./assets/images/ios.png

  - name: Ruby on Rails
    web_url: https://rubyonrails.org/
    image_url: https://rubyonrails.org/images/rails-logo.svg
